sequenceDiagram
    actor User
    participant Browser
    participant Server

    User->>Browser: Open MPA page
    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    Server-->>Browser: HTML Page (200)
    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate Server
    Server-->>Browser: the css file (200)
    deactivate Server

   Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate Server
        Server-->>Browser: the JavaScript file (200)
    deactivate Server

    Note right of Browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate Server
    Server-->>Browser: JSON file
    deactivate Server

    Note right of Browser: The browser executes the callback function that renders the notes



    User->>Browser: new_note
    Browser->>Server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    Server-->>Browser: Redirect (302) = https://studies.cs.helsinki.fi/exampleapp/notes


    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    Server-->>Browser: Updated HTML Page document (200)
    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate Server
     Server-->>Browser: main css file (200)
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate Server
    Server-->>Browser: the JavaScript file (200)
    deactivate Server

    Note right of Browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
     activate Server
    Server-->>Browser: [{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]
    deactivate Server

    Note right of Browser: The browser executes the callback function that renders the notes
