sequenceDiagram
    actor User
    participant Browser
    participant JSEvent
    participant Server

    User->>Browser: Open SPA URL
    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    Server-->>Browser: HTML

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa.css
    Server-->>Browser: css

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    Server-->>Browser: JavaScript

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa.json
    Server-->>Browser: Notes JSON


    User->>Browser: Adde a new 

    activate JSEvent
    Browser->>JSEvent: GET https://studies.cs.helsinki.fi/exampleapp/new-note
    JSEvent->>Server: Fetch request
    Server->>JSEvent: updates part of page only (JSON)
    JSEvent->>Browser: Updated Page

    deactivate JSEvent
